
AAdventumGather = {
	"QLU NEW: 179 [Dwarven Outfitters]", -- [1]
	"QLU OBJECTIVE: Tough Wolf Meat: 1/8 false", -- [2]
	"QLU OBJECTIVE: Tough Wolf Meat: 2/8 false", -- [3]
	"QLU OBJECTIVE: Tough Wolf Meat: 3/8 false", -- [4]
	"LEVEL: 2", -- [5]
	"QLU OBJECTIVE: Tough Wolf Meat: 4/8 false", -- [6]
	"QLU OBJECTIVE: Tough Wolf Meat: 5/8 false", -- [7]
	"QLU OBJECTIVE: Tough Wolf Meat: 6/8 false", -- [8]
	"QUEST_TURNED_IN: {179} [Dwarven Outfitters] Dun Morogh:Coldridge Valley", -- [9]
	"QLU NEW: {3110} [Hallowed Rune] Dun Morogh:Coldridge Valley", -- [10]
	"QLU NEW: {233} [Coldridge Valley Mail Delivery] Dun Morogh:Coldridge Valley", -- [11]
	"QLU NEW: {170} [A New Threat] Dun Morogh:Coldridge Valley", -- [12]
	"LEVEL: 3", -- [13]
	"QUEST_TURNED_IN: {170} [A New Threat] Dun Morogh:Coldridge Valley", -- [14]
	"QLU NEW: {3361} [A Refugee's Quandary] Anvilmar", -- [15]
	"QUEST_TURNED_IN: {3110} [Hallowed Rune] Anvilmar", -- [16]
	"QUEST_TURNED_IN: {233} [Coldridge Valley Mail Delivery] Dun Morogh:Coldridge Valley", -- [17]
	"QLU NEW: {234} [Coldridge Valley Mail Delivery] Dun Morogh:Coldridge Valley", -- [18]
	"QLU NEW: {183} [The Boar Hunter] Dun Morogh:Coldridge Valley", -- [19]
	"LEVEL: 4", -- [20]
	"QUEST_TURNED_IN: {183} [The Boar Hunter] Dun Morogh:Coldridge Valley", -- [21]
	"QUEST_TURNED_IN: {234} [Coldridge Valley Mail Delivery] Dun Morogh:Coldridge Valley", -- [22]
	"QLU NEW: {182} [The Troll Cave] Dun Morogh:Coldridge Valley", -- [23]
	"QLU NEW: {3364} [Scalding Mornbrew Delivery] Dun Morogh:Coldridge Valley", -- [24]
	"QUEST_TURNED_IN: {3364} [Scalding Mornbrew Delivery] Anvilmar", -- [25]
	"QLU NEW: {3365} [Bring Back the Mug] Anvilmar", -- [26]
	"QUEST_TURNED_IN: {3365} [Bring Back the Mug] Dun Morogh:Coldridge Valley", -- [27]
	"LEVEL: 5", -- [28]
	"QUEST_TURNED_IN: {182} [The Troll Cave] Dun Morogh:Coldridge Valley", -- [29]
	"QUEST_TURNED_IN: {3361} [A Refugee's Quandary] Anvilmar", -- [30]
	"QLU NEW: {5626} [In Favor of the Light] Anvilmar", -- [31]
	"INSERTED: dorfs and gnomes should sell yer bread and keep tough jerky for food", -- [32]
	"INSERTED: priests get a little extra quest here", -- [33]
	"QUEST_TURNED_IN: {282} [Senir's Observations] Dun Morogh:Coldridge Pass", -- [34]
	"QLU NEW: {420} [Senir's Observations] Dun Morogh:Coldridge Pass", -- [35]
	"QLU NEW: {2160} [Supplies to Tannok] Dun Morogh:Coldridge Pass", -- [36]
	"QUEST_TURNED_IN: {420} [Senir's Observations] Dun Morogh:Kharanos", -- [37]
	"LEVEL: 6", -- [38]
	"QUEST_TURNED_IN: {5626} [In Favor of the Light] Dun Morogh:Thunderbrew Distillery", -- [39]
	"QLU NEW: {5625} [Garments of the Light] Dun Morogh:Thunderbrew Distillery", -- [40]
	"QUEST_TURNED_IN: {2160} [Supplies to Tannok] Dun Morogh:Thunderbrew Distillery", -- [41]
	"QLU NEW: {384} [Beer Basted Boar Ribs] Dun Morogh:Kharanos", -- [42]
	"QLU NEW: {400} [Tools for Steelgrill] Dun Morogh:Kharanos", -- [43]
	"QUEST_TURNED_IN: {5625} [Garments of the Light] Dun Morogh:Thunderbrew Distillery", -- [44]
	"QLU NEW: {317} [Stocking Jetsteam] Dun Morogh:Steelgrill's Depot", -- [45]
	"QLU NEW: {313} [The Grizzled Den] Dun Morogh:Steelgrill's Depot", -- [46]
	"QUEST_TURNED_IN: {400} [Tools for Steelgrill] Dun Morogh:Steelgrill's Depot", -- [47]
	"QLU NEW: {5541} [Ammo for Rumbleshot] Dun Morogh:Steelgrill's Depot", -- [48]
}
AAdventumGatherCount = 48
