
AAdventumGather = {
	"QLU NEW: 179 [Dwarven Outfitters]", -- [1]
	"QLU OBJECTIVE: Tough Wolf Meat: 1/8 false", -- [2]
	"QLU OBJECTIVE: Tough Wolf Meat: 2/8 false", -- [3]
	"QLU OBJECTIVE: Tough Wolf Meat: 3/8 false", -- [4]
	"LEVEL: 2", -- [5]
	"QLU OBJECTIVE: Tough Wolf Meat: 4/8 false", -- [6]
	"QLU OBJECTIVE: Tough Wolf Meat: 5/8 false", -- [7]
	"QLU OBJECTIVE: Tough Wolf Meat: 6/8 false", -- [8]
	"QUEST_TURNED_IN: {179} [Dwarven Outfitters] Dun Morogh:Coldridge Valley", -- [9]
	"QLU NEW: {3110} [Hallowed Rune] Dun Morogh:Coldridge Valley", -- [10]
	"QLU NEW: {233} [Coldridge Valley Mail Delivery] Dun Morogh:Coldridge Valley", -- [11]
	"QLU NEW: {170} [A New Threat] Dun Morogh:Coldridge Valley", -- [12]
	"LEVEL: 3", -- [13]
	"QUEST_TURNED_IN: {170} [A New Threat] Dun Morogh:Coldridge Valley", -- [14]
	"QLU NEW: {3361} [A Refugee's Quandary] Anvilmar", -- [15]
	"QUEST_TURNED_IN: {3110} [Hallowed Rune] Anvilmar", -- [16]
	"QUEST_TURNED_IN: {233} [Coldridge Valley Mail Delivery] Dun Morogh:Coldridge Valley", -- [17]
	"QLU NEW: {234} [Coldridge Valley Mail Delivery] Dun Morogh:Coldridge Valley", -- [18]
	"QLU NEW: {183} [The Boar Hunter] Dun Morogh:Coldridge Valley", -- [19]
	"LEVEL: 4", -- [20]
	"QUEST_TURNED_IN: {183} [The Boar Hunter] Dun Morogh:Coldridge Valley", -- [21]
	"QUEST_TURNED_IN: {234} [Coldridge Valley Mail Delivery] Dun Morogh:Coldridge Valley", -- [22]
	"QLU NEW: {182} [The Troll Cave] Dun Morogh:Coldridge Valley", -- [23]
	"QLU NEW: {3364} [Scalding Mornbrew Delivery] Dun Morogh:Coldridge Valley", -- [24]
	"QUEST_TURNED_IN: {3364} [Scalding Mornbrew Delivery] Anvilmar", -- [25]
	"QLU NEW: {3365} [Bring Back the Mug] Anvilmar", -- [26]
	"QUEST_TURNED_IN: {3365} [Bring Back the Mug] Dun Morogh:Coldridge Valley", -- [27]
	"LEVEL: 5", -- [28]
	"QUEST_TURNED_IN: {182} [The Troll Cave] Dun Morogh:Coldridge Valley", -- [29]
	"QLU NEW: {218} [Some Journal] Dun Morogh:Steelgrill's Depot", -- [45]
	"QLU NEW: {282} [Senir's Observations] Dun Morogh:Steelgrill's Depot", -- [45]
	"QUEST_TURNED_IN: {3361} [A Refugee's Quandary] Anvilmar", -- [30]
	"QLU NEW: {5626} [In Favor of the Light] Anvilmar", -- [31]
	"INSERTED: dorfs and gnomes should sell yer bread and keep tough jerky for food", -- [32]
	"INSERTED: priests get a little extra quest here", -- [33]
	"QUEST_TURNED_IN: {282} [Senir's Observations] Dun Morogh:Coldridge Pass", -- [34]
	"QLU NEW: {420} [Senir's Observations] Dun Morogh:Coldridge Pass", -- [35]
	"QLU NEW: {2160} [Supplies to Tannok] Dun Morogh:Coldridge Pass", -- [36]
	"QUEST_TURNED_IN: {420} [Senir's Observations] Dun Morogh:Kharanos", -- [37]
	"LEVEL: 6", -- [38]
	"QUEST_TURNED_IN: {5626} [In Favor of the Light] Dun Morogh:Thunderbrew Distillery", -- [39]
	"QLU NEW: {5625} [Garments of the Light] Dun Morogh:Thunderbrew Distillery", -- [40]
	"QUEST_TURNED_IN: {2160} [Supplies to Tannok] Dun Morogh:Thunderbrew Distillery", -- [41]
	"QLU NEW: {384} [Beer Basted Boar Ribs] Dun Morogh:Kharanos", -- [42]
	"QLU NEW: {400} [Tools for Steelgrill] Dun Morogh:Kharanos", -- [43]
	"QUEST_TURNED_IN: {5625} [Garments of the Light] Dun Morogh:Thunderbrew Distillery", -- [44]
	"QLU NEW: {317} [Stocking Jetsteam] Dun Morogh:Steelgrill's Depot", -- [45]
	"QLU NEW: {313} [The Grizzled Den] Dun Morogh:Steelgrill's Depot", -- [46]
	"QUEST_TURNED_IN: {400} [Tools for Steelgrill] Dun Morogh:Steelgrill's Depot", -- [47]
	"QLU NEW: {5541} [Ammo for Rumbleshot] Dun Morogh:Steelgrill's Depot", -- [48]
	"QLU NEW: {5541} [Ammo for Rumbleshot] :", -- [49]
	"QLU NEW: {317} [Stocking Jetsteam] :", -- [50]
	"QLU NEW: {313} [The Grizzled Den] :", -- [51]
	"QLU NEW: {384} [Beer Basted Boar Ribs] :", -- [52]
	"QLU NEW: {783} [A Threat Within] Elwynn Forest:Northshire Valley", -- [53]
	"QUEST_TURNED_IN: {783} [A Threat Within] Elwynn Forest:Northshire Abbey", -- [54]
	"QLU NEW: {7} [Kobold Camp Cleanup] Elwynn Forest:Northshire Abbey", -- [55]
	"QLU NEW: {33} [Wolves Across the Border] Elwynn Forest:Northshire Valley", -- [56]
	"QUEST_TURNED_IN: {33} [Wolves Across the Border] Elwynn Forest:Northshire Valley", -- [57]
	"QUEST_TURNED_IN: {7} [Kobold Camp Cleanup] Elwynn Forest:Northshire Abbey", -- [58]
	"QLU NEW: {15} [Investigate Echo Ridge] Elwynn Forest:Northshire Abbey", -- [59]
	"QLU NEW: {18} [Brotherhood of Thieves] Elwynn Forest:Northshire Valley", -- [60]
	"QUEST_TURNED_IN: {15} [Investigate Echo Ridge] Elwynn Forest:Northshire Abbey", -- [61]
	"QLU NEW: {21} [Skirmish at Echo Ridge] Elwynn Forest:Northshire Abbey", -- [62]
	"QUEST_REMOVED: 21 [Skirmish at Echo Ridge]", -- [63]
	"QLU NEW: {21} [Skirmish at Echo Ridge] Elwynn Forest:Northshire Abbey", -- [64]
	"QUEST_REMOVED: 21 [Skirmish at Echo Ridge]", -- [65]
	"QLU NEW: {21} [Skirmish at Echo Ridge] Elwynn Forest:Northshire Abbey", -- [66]
	"LEVEL: 7", -- [67]
	"QUEST_TURNED_IN: {21} [Skirmish at Echo Ridge] Elwynn Forest:Northshire Abbey", -- [68]
	"QLU NEW: {54} [Report to Goldshire] Elwynn Forest:Northshire Abbey", -- [69]
	"QUEST_REMOVED: 54 [Report to Goldshire]", -- [70]
	"INSERTED: cause it takes bag space", -- [71]
	"QUEST_TURNED_IN: {18} [Brotherhood of Thieves] Elwynn Forest:Northshire Valley", -- [72]
	"QLU NEW: {3903} [Milly Osworth] Elwynn Forest:Northshire Valley", -- [73]
	"QLU NEW: {6} [Bounty on Garrick Padfoot] Elwynn Forest:Northshire Valley", -- [74]
	"QUEST_TURNED_IN: {3903} [Milly Osworth] Elwynn Forest:Northshire Valley", -- [75]
	"QLU NEW: {3904} [Milly's Harvest] Elwynn Forest:Northshire Valley", -- [76]
	"QUEST_TURNED_IN: {3904} [Milly's Harvest] Elwynn Forest:Northshire Valley", -- [77]
	"QLU NEW: {3905} [Grape Manifest] Elwynn Forest:Northshire Valley", -- [78]
	"QUEST_TURNED_IN: {6} [Bounty on Garrick Padfoot] Elwynn Forest:Northshire Valley", -- [79]
	"QUEST_TURNED_IN: {3905} [Grape Manifest] Elwynn Forest:Northshire Abbey", -- [80]
	"QLU NEW: {54} [Report to Goldshire] Elwynn Forest:Northshire Abbey", -- [81]
	"QLU NEW: {2158} [Rest and Relaxation] Elwynn Forest:Northshire Valley", -- [82]
	"QUEST_TURNED_IN: {54} [Report to Goldshire] Elwynn Forest:Goldshire", -- [83]
	"QUEST_TURNED_IN: {2158} [Rest and Relaxation] Lion's Pride Inn:", -- [86]

	"QLU NEW: {62} [The Fargodeep Mine] Elwynn Forest:Goldshire", -- [84]
	"QLU NEW: {60} [Kobold Candles] Lion's Pride Inn:", -- [85]
	"QLU NEW: {40} [A Fishy Peril] Elwynn Forest:Goldshire", -- [87]
	"QLU NEW: {47} [Gold Dust Exchange] Elwynn Forest:Goldshire", -- [88]
	"QUEST_REMOVED: 40 [A Fishy Peril]", -- [89]
	"QLU NEW: {332} [Wine Shop Advert] Stormwind City:Trade District", -- [90]
	"INSERTED: these should have been done much ealier", -- [91]
	"QLU NEW: {333} [Harlan Needs a Resupply] Stormwind City:Trade District", -- [92]
	"QUEST_TURNED_IN: {333} [Harlan Needs a Resupply] Stormwind City:The Canals", -- [93]
	"QLU NEW: {334} [Package for Thurman] Stormwind City:The Canals", -- [94]
	"QUEST_TURNED_IN: {334} [Package for Thurman] Stormwind City:Mage Quarter", -- [95]
	"QUEST_TURNED_IN: {332} [Wine Shop Advert] Stormwind City:The Canals", -- [96]


	"QLU NEW: 47 [Gold Dust Exchange]", -- [98]
	"QUEST_TURNED_IN: 40 [A Fishy Peril]", -- [99]
	"QLU NEW: 35 [Further Concerns]", -- [100]
	"QLU NEW: 62 [The Fargodeep Mine]", -- [101]
	"QLU NEW: 60 [Kobold Candles]", -- [102]
	"QLU OBJECTIVE: Gold Dust: 1/10 false", -- [103]
	"QLU NEW: 106 [Young Lovers]", -- [104]
	"QUEST_TURNED_IN: 106 [Young Lovers]", -- [105]




	"QLU NEW: 111 [Speak with Gramma]", -- [106]
	"QLU NEW: 85 [Lost Necklace]", -- [107]
	"QLU NEW: 88 [Princess Must Die!]", -- [108]
	"QUEST_TURNED_IN: 111 [Speak with Gramma]", -- [109]
	"QLU NEW: 107 [Note to William]", -- [110]
	"QUEST_TURNED_IN: 107 [Note to William]", -- [111]
	"QLU NEW: 112 [Collecting Kelp]", -- [112]
	"QLU OBJECTIVE: Crystal Kelp Frond: 1/4 false", -- [113]
	"QLU OBJECTIVE: Crystal Kelp Frond: 2/4 false", -- [114]
	"QLU OBJECTIVE: Crystal Kelp Frond: 3/4 false", -- [115]
	"QLU OBJECTIVE: Crystal Kelp Frond: 4/4 true", -- [116]
	"QUEST_TURNED_IN: 112 [Collecting Kelp]", -- [117]


	"QLU NEW: 114 [The Escape]", -- [118]


	"QUEST_TURNED_IN: 85 [Lost Necklace]", -- [119]
	"QLU NEW: 86 [Pie for Billy]", -- [120]
	"LEVEL: 9", -- [121]
	"QUEST_TURNED_IN: 114 [The Escape]", -- [122]
	"QUEST_TURNED_IN: 86 [Pie for Billy]", -- [123]
	"QLU NEW: 84 [Back to Billy]", -- [124]
	"QUEST_TURNED_IN: 84 [Back to Billy]", -- [125]
	"QLU NEW: 87 [Goldtooth]", -- [126]
	"QLU OBJECTIVE: Gold Dust: 2/10 false", -- [127]
	"QLU OBJECTIVE: Large Candle: 1/8 false", -- [128]
	"QLU OBJECTIVE: Scout through the Fargodeep Mine true", -- [129]
	"QLU OBJECTIVE: Large Candle: 2/8 false", -- [130]
	"QLU OBJECTIVE: Gold Dust: 3/10 false", -- [131]
	"QLU OBJECTIVE: Large Candle: 3/8 false", -- [132]
	"QLU OBJECTIVE: Gold Dust: 4/10 false", -- [133]
	"QLU OBJECTIVE: Large Candle: 4/8 false", -- [134]
	"QLU OBJECTIVE: Bernice's Necklace: 1/1 true", -- [135]
	"QLU OBJECTIVE: Gold Dust: 5/10 false", -- [136]
	"QLU OBJECTIVE: Large Candle: 5/8 false", -- [137]
	"QLU OBJECTIVE: Large Candle: 6/8 false", -- [138]
	"QLU OBJECTIVE: Large Candle: 7/8 false", -- [139]
	"QLU OBJECTIVE: Gold Dust: 6/10 false", -- [140]
	"QLU OBJECTIVE: Large Candle: 8/8 true", -- [141]
	"QLU OBJECTIVE: Gold Dust: 7/10 false", -- [142]
	"QLU OBJECTIVE: Gold Dust: 8/10 false", -- [143]
	"QLU OBJECTIVE: Gold Dust: 9/10 false", -- [144]
	"QLU OBJECTIVE: Gold Dust: 10/10 true", -- [145]
	"QUEST_TURNED_IN: 87 [Goldtooth]", -- [146]
	"QUEST_TURNED_IN: 47 [Gold Dust Exchange]", -- [147]
	"QUEST_TURNED_IN: 62 [The Fargodeep Mine]", -- [148]
	"QLU NEW: 76 [The Jasperlode Mine]", -- [149]
	"QLU NEW: 109 [Report to Gryan Stoutmantle]", -- [150]
	"QUEST_TURNED_IN: 60 [Kobold Candles]", -- [151]
	"QLU NEW: 61 [Shipment to Stormwind]", -- [152]



	"QLU NEW: 1097 [Elmore's Task]", -- [153]
	"INSERTED: ", -- [154]
	"INSERTED: get to level 10 before after quest turn in in GS so you can get class quest", -- [155]
	"QLU OBJECTIVE: Scout through the Jasperlode Mine true", -- [156]
	"LEVEL: 10", -- [157]
	"QLU NEW: 184 [Furlbrow's Deed]", -- [158]
	"QUEST_TURNED_IN: 76 [The Jasperlode Mine]", -- [159]
	"QLU NEW: 239 [Westbrook Garrison Needs Help!]", -- [160]
	"QLU NEW: 1638 [A Warrior's Training]", -- [161]
	"QLU NEW: 332 [Wine Shop Advert]", -- [162]
	"QUEST_TURNED_IN: 61 [Shipment to Stormwind]", -- [163]
	"QLU NEW: 333 [Harlan Needs a Resupply]", -- [164]
	"QUEST_TURNED_IN: 333 [Harlan Needs a Resupply]", -- [165]
	"QLU NEW: 334 [Package for Thurman]", -- [166]
	"QUEST_TURNED_IN: 332 [Wine Shop Advert]", -- [167]
	"QUEST_TURNED_IN: 334 [Package for Thurman]", -- [168]
	"QUEST_TURNED_IN: 1638 [A Warrior's Training]", -- [169]
	"QLU NEW: 1639 [Bartleby the Drunk]", -- [170]
	"QUEST_TURNED_IN: 1639 [Bartleby the Drunk]", -- [171]
	"QLU NEW: 1640 [Beat Bartleby]", -- [172]
	"QLU OBJECTIVE: Beat Bartleby true", -- [173]
	"QUEST_TURNED_IN: 1640 [Beat Bartleby]", -- [174]
	"QLU NEW: 1665 [Bartleby's Mug]", -- [175]
	"QUEST_TURNED_IN: 1665 [Bartleby's Mug]", -- [176]
	"QLU NEW: 1666 [Marshal Haggard]", -- [177]
	"QLU OBJECTIVE: Brass Collar: 1/1 true", -- [178]
	"LEVEL: 11", -- [179]
	"QUEST_TURNED_IN: 35 [Further Concerns]", -- [180]
	"QLU NEW: 37 [Find the Lost Guards]", -- [181]
	"QLU NEW: 52 [Protect the Frontier]", -- [182]
	"QLU NEW: 83 [Red Linen Goods]", -- [183]
	"QLU NEW: 5545 [A Bundle of Trouble]", -- [184]
	"QUEST_TURNED_IN: 1666 [Marshal Haggard]", -- [185]
	"QLU NEW: 1667 [Dead-tooth Jack]", -- [186]
	"QLU OBJECTIVE: Red Linen Bandana: 1/6 false", -- [187]
	"QLU OBJECTIVE: Marshal Haggard's Badge: 1/1 true", -- [188]
	"QUEST_TURNED_IN: 1667 [Dead-tooth Jack]", -- [189]
	"QLU OBJECTIVE: Prowler slain: 1/8 false", -- [190]
	"QLU OBJECTIVE: Prowler slain: 2/8 false", -- [191]
	"QLU OBJECTIVE: Bundle of Wood: 1/8 false", -- [192]
	"QLU OBJECTIVE: Bundle of Wood: 2/8 false", -- [193]
	"QLU OBJECTIVE: Bundle of Wood: 3/8 false", -- [194]
	"QUEST_TURNED_IN: 37 [Find the Lost Guards]", -- [195]
	"QLU NEW: 45 [Discover Rolf's Fate]", -- [196]
	"QUEST_TURNED_IN: 45 [Discover Rolf's Fate]", -- [197]
	"QLU NEW: 71 [Report to Thomas]", -- [198]
	"QLU OBJECTIVE: Bundle of Wood: 4/8 false", -- [199]
	"QLU OBJECTIVE: Prowler slain: 3/8 false", -- [200]
	"QLU OBJECTIVE: Young Forest Bear slain: 1/5 false", -- [201]
	"QLU OBJECTIVE: Bundle of Wood: 5/8 false", -- [202]
	"QLU OBJECTIVE: Bundle of Wood: 6/8 false", -- [203]
	"QLU OBJECTIVE: Bundle of Wood: 7/8 false", -- [204]
	"QLU OBJECTIVE: Bundle of Wood: 8/8 true", -- [205]
	"QUEST_TURNED_IN: 71 [Report to Thomas]", -- [206]
	"QLU NEW: 39 [Deliver Thomas' Report]", -- [207]
	"QLU OBJECTIVE: Prowler slain: 4/8 false", -- [208]
	"QLU OBJECTIVE: Prowler slain: 5/8 false", -- [209]
	"QLU OBJECTIVE: Young Forest Bear slain: 2/5 false", -- [210]
	"QLU OBJECTIVE: Prowler slain: 6/8 false", -- [211]
	"QLU OBJECTIVE: Prowler slain: 7/8 false", -- [212]
	"QLU OBJECTIVE: Young Forest Bear slain: 3/5 false", -- [213]
	"QLU OBJECTIVE: Young Forest Bear slain: 4/5 false", -- [214]
	"QLU OBJECTIVE: Prowler slain: 8/8 true", -- [215]
	"QLU OBJECTIVE: Young Forest Bear slain: 5/5 true", -- [216]
	"QUEST_TURNED_IN: 5545 [A Bundle of Trouble]", -- [217]
	"QUEST_TURNED_IN: 52 [Protect the Frontier]", -- [218]
	"QLU OBJECTIVE: Red Linen Bandana: 2/6 false", -- [219]
	"QLU OBJECTIVE: Red Linen Bandana: 3/6 false", -- [220]
	"QLU OBJECTIVE: Red Linen Bandana: 4/6 false", -- [221]
	"QLU OBJECTIVE: Red Linen Bandana: 5/6 false", -- [222]
	"QLU OBJECTIVE: Red Linen Bandana: 6/6 true", -- [223]
	"QUEST_TURNED_IN: 39 [Deliver Thomas' Report]", -- [224]
	"QLU NEW: 59 [Cloth and Leather Armor]", -- [225]
	"QUEST_TURNED_IN: 239 [Westbrook Garrison Needs Help!]", -- [226]
	"QLU NEW: 11 [Riverpaw Gnoll Bounty]", -- [227]
	"QLU NEW: 176 [Wanted:  \"Hogger\"]", -- [228]
	"QLU OBJECTIVE: Huge Gnoll Claw: 1/1 true", -- [229]
	"QUEST_TURNED_IN: 176 [Wanted:  \"Hogger\"]", -- [230]
	"LEVEL: 12", -- [231]
	"QUEST_TURNED_IN: 88 [Princess Must Die!]", -- [232]
	"QUEST_TURNED_IN: 59 [Cloth and Leather Armor]", -- [233]
	"QUEST_TURNED_IN: 83 [Red Linen Goods]", -- [234]
	"QLU NEW: 46 [Bounty on Murlocs]", -- [235]
	"QLU OBJECTIVE: Torn Murloc Fin: 1/8 false", -- [236]
	"QLU OBJECTIVE: Torn Murloc Fin: 2/8 false", -- [237]
	"QLU OBJECTIVE: Torn Murloc Fin: 3/8 false", -- [238]
	"QLU OBJECTIVE: Torn Murloc Fin: 4/8 false", -- [239]
	"QLU OBJECTIVE: Torn Murloc Fin: 5/8 false", -- [240]
	"QLU OBJECTIVE: Torn Murloc Fin: 6/8 false", -- [241]
	"QLU OBJECTIVE: Torn Murloc Fin: 7/8 false", -- [242]
	"QLU OBJECTIVE: Torn Murloc Fin: 8/8 true", -- [243]
	"QLU OBJECTIVE: Painted Gnoll Armband: 1/8 false", -- [244]
	"QLU OBJECTIVE: Painted Gnoll Armband: 2/8 false", -- [245]
	"QLU OBJECTIVE: Painted Gnoll Armband: 3/8 false", -- [246]
	"QLU OBJECTIVE: Painted Gnoll Armband: 4/8 false", -- [247]
	"QLU OBJECTIVE: Painted Gnoll Armband: 5/8 false", -- [248]
	"QLU OBJECTIVE: Painted Gnoll Armband: 6/8 false", -- [249]
	"QUEST_TURNED_IN: 46 [Bounty on Murlocs]", -- [250]
	"QLU OBJECTIVE: Painted Gnoll Armband: 7/8 false", -- [251]
	"QLU OBJECTIVE: Painted Gnoll Armband: 8/8 true", -- [252]
	"QUEST_TURNED_IN: 11 [Riverpaw Gnoll Bounty]", -- [253]
	"QUEST_TURNED_IN: 184 [Furlbrow's Deed]", -- [254]
}
AAdventumGatherCount = 96
